---
# tasks file for duckdns

- name: "Add the {{ duckdns_group }} group"
  ansible.builtin.group:
    name: "{{ duckdns_group }}"
    state: present

- name: "Add the {{ duckdns_user }} user"
  ansible.builtin.user:
    name: "{{ duckdns_user }}"
    comment: "duckdns user"
    group: "{{ duckdns_group }}"
    state: present

- name: Install require packages
  ansible.builtin.include_tasks: ubuntu_packages.yml
  when: ansible_distribution == "Ubuntu"

- name: Ensures required directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
  with_items:
      - "{{ duckdns_project_root }}"
      - "{{ duckdns_project_log }}"

- name: Setup cron executable
  ansible.builtin.template:
    src: "templates/duck.sh"
    dest: "{{ duckdns_project_root }}/duck.sh"
    owner: "{{ duckdns_user }}"
    group: "{{ duckdns_group }}"
    mode: 700

# 
- name: "Create duck.sh cron file under /etc/cron.d"
  ansible.builtin.cron:
    name: DuckDNS autoupdate
    special_time: hourly
    user: root
    job: "{{ duckdns_project_root }}/duck.sh"
    cron_file: duckdns-updater
  notify: reload cron service

- name: Update the IP Address Now
  ansible.builtin.shell: "{{ duckdns_project_root }}/duck.sh"
  changed_when: false
  when: duckdns_update_now
